<div class="nav flex-column nav-tabs h-100" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
    <a class="nav-link active" id="vert-tabs-ombs-tab_past" data-toggle="pill" href="#vert-tabs-ombs_past" role="tab" aria-controls="vert-tabs-ombs_past" aria-selected="true" wire:ignore>OMBS & VOE</a>
    <a class="nav-link" id="vert-tabs-3mbs-tab_past" data-toggle="pill" href="#vert-tabs-3mbs_past" role="tab" aria-controls="vert-tabs-3mbs_past" aria-selected="false" wire:ignore>3MBS</a>
    <a class="nav-link" id="vert-tabs-dscr-tab_past" data-toggle="pill" href="#vert-tabs-dscr_past" role="tab" aria-controls="vert-tabs-dscr_past" aria-selected="false" wire:ignore>Business Purpose / DSCR</a>
    <a class="nav-link" id="vert-tabs-non-prime-ws-tab_past" data-toggle="pill" href="#vert-tabs-non-prime-ws_past" role="tab" aria-controls="vert-tabs-non-prime-ws_past" aria-selected="false" wire:ignore>Non-Prime Wholesale</a>
    <a class="nav-link" id="vert-tabs-jumbo-prime-ws-tab_past" data-toggle="pill" href="#vert-tabs-jumbo-prime-ws_past" role="tab" aria-controls="vert-tabs-jumbo-prime-ws_past" aria-selected="false" wire:ignore>Jumbo Prime Wholesale</a>
    <a class="nav-link" id="vert-tabs-small-balance-multifamily-tab_past" data-toggle="pill" href="#vert-tabs-small-balance-multifamily_past" role="tab" aria-controls="vert-tabs-small-balance-multifamily_past" aria-selected="false" wire:ignore>Small Balance Multifamily</a>
    <a class="nav-link" id="vert-tabs-ff-stabilized-bridge-sfr-tab_past" data-toggle="pill" href="#vert-tabs-ff-stabilized-bridge-sfr_past" role="tab" aria-controls="vert-tabs-ff-stabilized-bridge-sfr_past" aria-selected="false" wire:ignore>Fix & Flip / Stabilized Bridge (SFR)</a>
    <a class="nav-link" id="vert-tabs-ff-stabilized-bridge-mf-tab_past" data-toggle="pill" href="#vert-tabs-ff-stabilized-bridge-mf_past" role="tab" aria-controls="vert-tabs-ff-stabilized-bridge-mf_past" aria-selected="false" wire:ignore>Fix & Flip / Stabilized Bridge (MF)</a>
    <a class="nav-link" id="vert-tabs-odf-tab_past" data-toggle="pill" href="#vert-tabs-odf_past" role="tab" aria-controls="vert-tabs-odf_past" aria-selected="false" wire:ignore>Outside Dodd-Frank<sup>®</sup></a>
    <a class="nav-link" id="vert-tabs-odfplus-tab_past" data-toggle="pill" href="#vert-tabs-odfplus_past" role="tab" aria-controls="vert-tabs-odfplus_past" aria-selected="false" wire:ignore>Outside Dodd-Frank<sup>®</sup>Plus</a>
  </div>