<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTurnTimesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //split table
        Schema::create('turn_times', function (Blueprint $table) {
            $table->id();
            $table->integer('user_id');
            $table->string('title_1');
            $table->integer('title_1_turn_time');
            $table->string('title_1_note');
            $table->string('sub_title_1a');
            $table->integer('sub_title_1a_turn_time');
            $table->string('sub_title_1a_note');
            $table->string('sub_title_1b');
            $table->integer('sub_title_1b_turn_time');
            $table->string('sub_title_1b_note');
            $table->string('sub_title_1c');
            $table->integer('sub_title_1c_turn_time');
            $table->string('sub_title_1c_note');
            $table->string('sub_title_1d');
            $table->integer('sub_title_1d_turn_time');
            $table->string('sub_title_1d_note');
            $table->string('sub_title_1e');
            $table->integer('sub_title_1e_turn_time');
            $table->string('sub_title_1e_note');
            $table->string('title_2');
            $table->integer('title_2_turn_time');
            $table->string('title_2_note');
            $table->string('sub_title_2a');
            $table->integer('sub_title_2a_turn_time');
            $table->string('sub_title_2a_note');
            $table->string('sub_title_2b');
            $table->integer('sub_title_2b_turn_time');
            $table->string('sub_title_2b_note');
            $table->string('sub_title_2c');
            $table->integer('sub_title_2c_turn_time');
            $table->string('sub_title_2c_note');
            $table->string('sub_title_2d');
            $table->integer('sub_title_2d_turn_time');
            $table->string('sub_title_2d_note');
            $table->string('sub_title_2e');
            $table->integer('sub_title_2e_turn_time');
            $table->string('sub_title_2e_note');
            $table->string('title_3');
            $table->integer('title_3_turn_time');
            $table->string('title_3_note');
            $table->string('sub_title_3a');
            $table->integer('sub_title_3a_turn_time');
            $table->string('sub_title_3a_note');
            $table->string('sub_title_3b');
            $table->integer('sub_title_3b_turn_time');
            $table->string('sub_title_3b_note');
            $table->string('sub_title_3c');
            $table->integer('sub_title_3c_turn_time');
            $table->string('sub_title_3c_note');
            $table->string('sub_title_3d');
            $table->integer('sub_title_3d_turn_time');
            $table->string('sub_title_3d_note');
            $table->string('sub_title_3e');
            $table->integer('sub_title_3e_turn_time');
            $table->string('sub_title_3e_note');
            $table->string('title_4');
            $table->integer('title_4_turn_time');
            $table->string('title_4_note');
            $table->string('sub_title_4a');
            $table->integer('sub_title_4a_turn_time');
            $table->string('sub_title_4a_note');
            $table->string('sub_title_4b');
            $table->integer('sub_title_4b_turn_time');
            $table->string('sub_title_4b_note');
            $table->string('sub_title_4c');
            $table->integer('sub_title_4c_turn_time');
            $table->string('sub_title_4c_note');
            $table->string('sub_title_4d');
            $table->integer('sub_title_4d_turn_time');
            $table->string('sub_title_4d_note');
            $table->string('sub_title_4e');
            $table->integer('sub_title_4e_turn_time');
            $table->string('sub_title_4e_note');
            $table->string('title_5');
            $table->integer('title_5_turn_time');
            $table->string('title_5_note');
            $table->string('sub_title_5a');
            $table->integer('sub_title_5a_turn_time');
            $table->string('sub_title_5a_note');
            $table->string('sub_title_5b');
            $table->integer('sub_title_5b_turn_time');
            $table->string('sub_title_5b_note');
            $table->string('sub_title_5c');
            $table->integer('sub_title_5c_turn_time');
            $table->string('sub_title_5c_note');
            $table->string('sub_title_5d');
            $table->integer('sub_title_5d_turn_time');
            $table->string('sub_title_5d_note');
            $table->string('sub_title_5e');
            $table->integer('sub_title_5e_turn_time');
            $table->string('sub_title_5e_note');
            $table->string('title_6');
            $table->integer('title_6_turn_time');
            $table->string('title_6_note');
            $table->string('sub_title_6a');
            $table->integer('sub_title_6a_turn_time');
            $table->string('sub_title_6a_note');
            $table->string('sub_title_6b');
            $table->integer('sub_title_6b_turn_time');
            $table->string('sub_title_6b_note');
            $table->string('sub_title_6c');
            $table->integer('sub_title_6c_turn_time');
            $table->string('sub_title_6c_note');
            $table->string('sub_title_6d');
            $table->integer('sub_title_6d_turn_time');
            $table->string('sub_title_6d_note');
            $table->string('sub_title_6e');
            $table->integer('sub_title_6e_turn_time');
            $table->string('sub_title_6e_note');
            $table->string('title_7');
            $table->integer('title_7_turn_time');
            $table->string('title_7_note');
            $table->string('sub_title_7a');
            $table->integer('sub_title_7a_turn_time');
            $table->string('sub_title_7a_note');
            $table->string('sub_title_7b');
            $table->integer('sub_title_7b_turn_time');
            $table->string('sub_title_7b_note');
            $table->string('sub_title_7c');
            $table->integer('sub_title_7c_turn_time');
            $table->string('sub_title_7c_note');
            $table->string('sub_title_7d');
            $table->integer('sub_title_7d_turn_time');
            $table->string('sub_title_7d_note');
            $table->string('sub_title_7e');
            $table->integer('sub_title_7e_turn_time');
            $table->string('sub_title_7e_note');
            $table->string('title_8');
            $table->integer('title_8_turn_time');
            $table->string('title_8_note');
            $table->string('sub_title_8a');
            $table->integer('sub_title_8a_turn_time');
            $table->string('sub_title_8a_note');
            $table->string('sub_title_8b');
            $table->integer('sub_title_8b_turn_time');
            $table->string('sub_title_8b_note');
            $table->string('sub_title_8c');
            $table->integer('sub_title_8c_turn_time');
            $table->string('sub_title_8c_note');
            $table->string('sub_title_8d');
            $table->integer('sub_title_8d_turn_time');
            $table->string('sub_title_8d_note');
            $table->string('sub_title_8e');
            $table->integer('sub_title_8e_turn_time');
            $table->string('sub_title_8e_note');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('turn_times');
    }
}
